#language:es
#author: KevinHernandez

Característica: como usuario de FutCol quiero inscribir mi equipo en un torneo para poder participar

  @suscripcion
  Escenario: Verificar la inscripcion exitosa de un equipo en FutCol

    Dado que el usuario se encuentra en la vista de suscripcion de FutCol
    Cuando ingrese todos los datos requeridos para la inscripcion del equipo
      | nombreEquipo | torneo | formaPago | nombreCapitan | correoCapitan         | documentoCapitan | contrasenaCapitan | generoCapitan | edadCapitan | fechaNacimientoCapitan | nombreJugador1 | emailJugador1      | documentoJugador1 | generoJugador1 | edadJugador1 | fechaNacimientoJugador1 | nombreJugador2 | emailJugador2       | documentoJugador2 | generoJugador2 | edadJugador2 | fechaNacimientoJugador2 | nombreJugador3 | emailJugador3         | documentoJugador3 | generoJugador3 | edadJugador3 | fechaNacimientoJugador3 | nombreJugador4 | emailJugador4         | documentoJugador4 | generoJugador4 | edadJugador4 | fechaNacimientoJugador4 | nombreJugador5 | emailJugador5        | documentoJugador5 | generoJugador5 | edadJugador5 | fechaNacimientoJugador5 | nombreJugador6 | emailJugador6       | documentoJugador6 | generoJugador6 | edadJugador6 | fechaNacimientoJugador6 | nombreJugador7 | emailJugador7       | documentoJugador7 | generoJugador7 | edadJugador7 | fechaNacimientoJugador7 |
      | Los Tigres   | Liga   | Efectivo  | Juan Rincon   | juan_rincon@gmail.com | 1001234554       | contrasena123     | Masculino     | 26          | 15-05-1999             | Pedro Lopez    | pedro_lp@gmail.com | 10257679981       | M              | 24           | 20-08-2001              | Carlos Ruiz    | carlos.iz@gmail.com | 1033551099        | M              | 25           | 20-03-2000              | Luis Torres    | luis_torres@gmail.com | 1033459987        | M              | 24           | 25-11-2000              | Miguel Diaz    | miguel.diaz@gmail.com | 1000323415        | M              | 23           | 14-07-2002              | Jorge Mendez   | jorge_1946@gmail.com | 1092326601        | M              | 25           | 05-09-2000              | Diego Castro   | diego.MFC@gmail.com | 1002751219        | M              | 22           | 20-12-2003              | Andres Vargas  | andres_01@gmail.com | 2346576456        | M              | 25           | 18-04-2000              |
    Entonces se debe verificar que la inscripcion haya sido exitosa